##### Numpy é uma biblioteca que permite trabalhar com dados em n-dimensões.Altamente eficiente para grandes conjuntos de dados. NumPy contém apenas um tipo de dado

In [2]:
import numpy as np

In [3]:
# cirando um array bidimensional

dados = np.array([[1, 2, 3, 4, 5, 6], [4, 6,7,8,9,10], [80,90,100,200,300,500]])
print(dados)

[[  1   2   3   4   5   6]
 [  4   6   7   8   9  10]
 [ 80  90 100 200 300 500]]


In [4]:
# elemento na linha 1 / coluna 2
dados[1, 2]

7

In [5]:
# seleciona toda a linha 1
dados[1]

array([ 4,  6,  7,  8,  9, 10])

In [6]:
# seleciona todas as linhas a partir da linha 1
dados[1:]

array([[  4,   6,   7,   8,   9,  10],
       [ 80,  90, 100, 200, 300, 500]])

In [7]:
# percorre todas as linhas, mas só seleciona os elementos da coluna 2
dados[:, 2]

array([  3,   7, 100])

In [8]:
# seleciona somente os elementos da coluna 1 e 2
dados[:, 1:3]

array([[  2,   3],
       [  6,   7],
       [ 90, 100]])

In [9]:
# na linha 1 seleciona apenas os elementos da colunas 1 e 2
dados[1, 1:3]

array([6, 7])

In [10]:
# percorre as linhas 1 e 2 e seleciona os elementos da coluna 4
dados[1:3, 4]

array([  9, 300])

##### Operações com vetores

In [11]:
# somar duas colunas

coluna1 = dados[:, 1]  # seleciona os elementos da coluna 1
coluna2 = dados[:, 2]  # seleciona os elementos da coluna 2

coluna = coluna1 + coluna2

print(coluna)

[  5  13 190]


In [12]:
# subtrair duas colunas

coluna1 = dados[:, 1]  # seleciona os elementos da coluna 1
coluna2 = dados[:, 2]  # seleciona os elementos da coluna 2

coluna = coluna1 - coluna2

print(coluna)

[ -1  -1 -10]


In [13]:
# multiplicar duas colunas

coluna1 = dados[:, 1]  # seleciona os elementos da coluna 1
coluna2 = dados[:, 2]  # seleciona os elementos da coluna 2

coluna = coluna1 * coluna2

print(coluna)

[   6   42 9000]


In [14]:
# dividir duas colunas

coluna1 = dados[:, 1]  # seleciona os elementos da coluna 1
coluna2 = dados[:, 2]  # seleciona os elementos da coluna 2

coluna = coluna1 / coluna2

print(coluna)

[0.66666667 0.85714286 0.9       ]


##### Métodos adicionais


In [15]:
# selecionar toda a linha 1 e selecionar o maior valor
dados_result = dados[1]
print(dados_result)

print(dados_result.max())

[ 4  6  7  8  9 10]
10


In [16]:
# pegar o menor valor

print(dados_result.min())

4


In [17]:
# pegar a média dessa linha
print(dados_result.mean())

7.333333333333333


In [18]:
# selecionar o valor máximo em cada coluna

dados.max(axis=0)

array([ 80,  90, 100, 200, 300, 500])

In [19]:
# valor máximo em cada linha

dados.max(axis=1)

array([  6,  10, 500])

In [20]:
# selecionar o menor valor na coluna

dados.min(axis=0)

array([1, 2, 3, 4, 5, 6])

In [21]:
dados.min(axis=1)

array([ 1,  4, 80])

##### Valores booleanos

In [22]:
array_1 = np.array([1, 2, 3, 4, 5])
array_2 = np.array(["blue", "blue", "red", "blue"])
array_3 = np.array([80.0, 103.4, 96.9, 200.3])

In [23]:
# compara se cada elemento do array é menor do que 3
# em seguida, é devolvido uma lista com todos os resultados
result_1 = array_1 < 3
print(result_1)

[ True  True False False False]


In [24]:
result_2 = array_2 == 'blue'
print(result_2)

[ True  True False  True]


In [25]:
result_3 = array_3 > 100
print(result_3)

[False  True False  True]


In [26]:
# filtar valores a partir de booleanos
# atribuo o resultado da opreção à nova variável
# dentro no meu array_3 e faço a comparação interna
# se cada elemento naquela posição é maior do 100
novo_array_3 = array_3[result_3]
print(novo_array_3)

[103.4 200.3]


##### Modificando arrays

In [27]:
a = np.array(['red', 'blue', 'black', 'blue', 'purple'])
a[0] = 'orange'
print(a)

['orange' 'blue' 'black' 'blue' 'purple']


In [ ]:
# podemos alterar vários elementos a partir de um dado intervalo
a[3:] = 'pink'
print(a)

In [29]:
# o mesmo é válido para arrays 2D
ones = np.array([[1, 1, 1, 1, 1],
                 [1, 1, 1, 1, 1],
                 [1, 1, 1, 1, 1]])
ones[1,2:] = 100
print(ones)

[[  1   1   1   1   1]
 [  1   1 100 100 100]
 [  1   1   1   1   1]]


In [30]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr_aux = arr > 2
# verifica em cada indice se o valor for maior do 2
# depois atribue o valor 100
arr[arr_aux] = 100

print(arr)

[  1   2 100 100 100 100 100 100 100 100]


In [33]:
# outra forma mais convencional
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[arr > 2] = 10
print(arr)

[ 1  2 10 10 10 10 10 10 10 10]


In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
x = arr.mean()
arr[arr < x] = x
print(arr)

[ 5  5  5  5  5  6  7  8  9 10]


In [44]:
# matriz 2D

arr = np.array([[1, 2, 3, 4, 5],
               [6, 7, 8, 9, 10],
               [11, 12, 13, 14, 15]])

# primeiro eu faço uma comparação pegando todas as linhas da coluna 1
# verifico se todos os elementos são maiores do que 5
# atribuo o valor 25 na coluna 1
arr[arr[:, 1] > 5, 1] = 25
arr 

array([[ 1,  2,  3,  4,  5],
       [ 6, 25,  8,  9, 10],
       [11, 25, 13, 14, 15]])